"""initial schema — create all tables from the ORM metadata (PRD §12).

Using metadata.create_all keeps the initial migration a faithful 1:1 mirror of the
models with zero drift risk. Subsequent changes should use autogenerated migrations.

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-23
"""
from __future__ import annotations

from alembic import op

from app.storage.db import models  # noqa: F401 - register tables
from app.storage.db.base import Base

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
